### ISSUE TITLE
Need to bump version of mock-xmlhttprequest to include creating blob bug fix

### ISSUE THREAD

**Issue by flying3615** [linearlabs-workspace/storybook-addon-mock#144]
Since the this repo still depends on a buggy version of mock-xmlhttprequest, it needs to bump to the latest version.
https://github.com/nutboltu/storybook-addon-mock/blob/ca710d41c80686a8c38041a6a9cbcfadb4d49a93/packages/mock-addon/package.json#L47

Bug report and has been fix in 8.0.0
https://github.com/berniegp/mock-xmlhttprequest/issues/31

**Comment by nutboltu** [comment]
Fixed in #143
