### ISSUE TITLE
Uncaught Error: Cannot find module '@storybook/blocks' 

### ISSUE THREAD

**Issue by emersonthis** [linearlabs-workspace/storybook-addon-mock#169]
I'm getting this error in the console: `Uncaught Error: Cannot find module '@storybook/blocks' `
The panels isn't appearing either.

I installed the addon `yarn add -D ...` and added it to the list of addons:

```
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    'storybook-addon-mock',
  ],
```

Then I set the mockData param for a component like this:

```
SomeComponent.parameters = {
  mockData: [
    {
      url: '/app/api/some/thing/1',
      method: 'GET',
      status: 200,
      response: { token: 'abc123' },
    },
```

Am I missing something? I tried `yarn add -D @storybook/blocks` and that did not fix the problem. I'm on node 16.14.2 in case that matters.

**Comment by nutboltu** [comment]
@emersonthis  I'm not sure if it's related to our package. Can you try uninstalling `storybook-addon-mock`?

**Comment by adampielach** [comment]
@emersonthis try different version if you don't use latest storybook. For my case it was version `3.2.0`. My storybook version is `6.5.16`

**Comment by skimchiebay** [comment]
I'm with storybook 6.5.16 and    "storybook-addon-mock": "^4.1.0". And this issue exists.

**Comment by nutboltu** [comment]
This package is added as a dependency in version [4.3.0](https://github.com/linearlabs-workspace/storybook-addon-mock/releases/tag/4.3.0)
