### ISSUE TITLE
[Feature] A way to disable the on/off button

### ISSUE THREAD

**Issue by sw-tracker** [linearlabs-workspace/storybook-addon-mock#170]
Hi there,

I would like to be able to disable the on/off button in the UI.

Thanks!

**Comment by sw-tracker** [comment]
We have storybook deployed in multiple environments and we leave the playground area activated so devs can play with the inputs. We would like to disable the on/off button in some environments so that the devs cant make REST calls from storybook.

**Comment by nutboltu** [comment]
In the latest release [4.2.0](https://github.com/linearlabs-workspace/storybook-addon-mock/releases/tag/4.2.0), you can use the `disableUsingOriginal` in the global configuration. Please see the https://storybook-addon-mock.netlify.app/?path=/docs/docs-advanced-setup--docs
