### ISSUE TITLE
[Feature] Should be able to abort fetch requests

### ISSUE THREAD

**Issue by plumpNation** [linearlabs-workspace/storybook-addon-mock#174]
Fetch supports passing an AbortController.signal in as an option.

https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort

This capability is not yet supported by storybook-addon-mock and I am hoping to implement it.

**Comment by nutboltu** [comment]
This fix is resolved in the latest release [4.2.0](https://github.com/linearlabs-workspace/storybook-addon-mock/releases/tag/4.2.0). Thanks, heap @plumpNation , for the awesome work!
