### ISSUE TITLE
XMLHttpRequest is not properly reflected when there's no mock matched

### ISSUE THREAD

**Issue by ItamarGronich** [linearlabs-workspace/storybook-addon-mock#178]
## The problem
Say i'm working on a story where i have 2 different requests, `api/a` and `api/b` where i want to mock one but not the other.
Then the request that's **NOT** mocked, doesn't have all the functionality of XMLHttpRequest.
For example, if the request returns anything other than `200` (202, 404, etc...) it gets swallowed and never returned. 
More over, no error callbacks and even handlers fire.
And the user supplied ready state is overriden.

## Why it happens
Here is where the `onreadystatechange` gets overriden. 
https://github.com/linearlabs-workspace/storybook-addon-mock/blob/master/packages/mock-addon/src/utils/faker.js#L168-L176
There's also no regard for anything other than strict 200 status.

Also error handlers are overriden too
https://github.com/linearlabs-workspace/storybook-addon-mock/blob/master/packages/mock-addon/src/utils/faker.js#L180-L185

## Proposed Solution
Reflect the entire xml http request as closely as possible to the real xhr object.

**Comment by nutboltu** [comment]
@ItamarGronich, thanks for raising this limitation.  Due to my workload, I can't commit to any fix as soon as possible. But I would highly encourage you to raise a PR with the fix.

**Comment by ItamarGronich** [comment]
@nutboltu Yeah sure will do

**Comment by ItamarGronich** [comment]
PR with fix in #181 
@nutboltu 

I would really appreciate if this fix can be also back-merged to 2.x  since we're using that and don't have capacity right now to upgrade.

Maybe i can ask a followup - since there's no summed up change log.
What was changed between 2.x-4.x ? 
What do we need to do to upgrade?

**Comment by nutboltu** [comment]
The change logs are in our [release notes](https://github.com/linearlabs-workspace/storybook-addon-mock/releases).

The major upgrade would be to storybook@7.

Currently, there's no mechanism of back merging the PR to the older version 😞

**Comment by ItamarGronich** [comment]
@nutboltu Can't i just checkout a 2.x.x release tag and rebase this pr onto it? then the release would bump the version to 2.x.x + 0.0.1 and publish. 
Wouldn't that work ?

**Comment by ItamarGronich** [comment]
@nutboltu Hey, i saw you merged my PR 🎉 
Any news on release?
I didn't see any.
And it seems CI has failed on the second merged PR.

**Comment by nutboltu** [comment]
This fix is resolved in the latest release [4.2.0](https://github.com/linearlabs-workspace/storybook-addon-mock/releases/tag/4.2.0). Thanks heap @ItamarGronich, for the awesome work!

**Comment by ItamarGronich** [comment]
Woohoo! Awseome! thanks @nutboltu 

Were you able to back merge and release a 2.x tag?

**Comment by ItamarGronich** [comment]
@nutboltu Does upgrading require me to upgrade to storybook 7? or can i stay on storybook 6?

**Comment by nutboltu** [comment]
@ItamarGronich you need to upgrade to Storybook 7.
