### ISSUE TITLE
Addon fails in Yarn pnp projects

### ISSUE THREAD

**Issue by yannbf** [linearlabs-workspace/storybook-addon-mock#183]
Hey there! Thanks for your work in this addon.

`@storybook/blocks` is a peer dependency of this addon, however not all users might have such dependency installed. Especially in modern package managers where peer dependencies are not installed by default.

Therefore, users who run projects with Yarn PnP will have the following issue:

```
.yarn/__virtual__/storybook-addon-mock-virtual-26f09ef4a8/.../node_modules/storybook-addon-mock/dist/esm/components/MockItem/index.js:6:44: 
ERROR: [plugin: @yarnpkg/esbuild-plugin-pnp] 
storybook-addon-mock tried to access @storybook/blocks (a peer dependency) but it isn't provided by your application; this makes the require call ambiguous and unsound.
```

**Comment by skimchiebay** [comment]
I'm also stuck with this.
Any hints about overriding it?

**Comment by yannbf** [comment]
Hey @skimchiebay a workaround is to install `@storybook/blocks` as a direct dependency.

**Comment by nutboltu** [comment]
This package is now added as a dependency in version [4.3.0](https://github.com/linearlabs-workspace/storybook-addon-mock/releases/tag/4.3.0)
