### ISSUE TITLE
getting blank pages when navigating around storybook after adding the mock addon

### ISSUE THREAD

**Issue by elirov** [linearlabs-workspace/storybook-addon-mock#184]
Here's a sample repo.

https://github.com/eSpoc/sb-broken-refresh

run:
pnpm i
pnpm storybook

click around in the browser and you should quickly get a blank screen.

if you comment out the mock addon plugin in .storybook/main.ts, everything works as expected (except there's no API mocking)

**Comment by elirov** [comment]
I do see this in the browser console as well.

Uncaught TypeError: Cannot read properties of undefined (reading 'disableUsingOriginal')
    at wu (index.js:42:42)
    at renderWithHooks (chunk-SJD7EFYL.js:69:936)
    at updateFunctionComponent (chunk-SJD7EFYL.js:69:48263)
    at beginWork (chunk-SJD7EFYL.js:71:21338)
    at HTMLUnknownElement.callCallback2 (chunk-SJD7EFYL.js:2:1918)
    at Object.invokeGuardedCallbackDev (chunk-SJD7EFYL.js:2:2442)
    at invokeGuardedCallback (chunk-SJD7EFYL.js:2:3700)
    at beginWork$1 (chunk-SJD7EFYL.js:90:39484)
    at performUnitOfWork (chunk-SJD7EFYL.js:90:21018)
    at workLoopSync (chunk-SJD7EFYL.js:90:20642)
wu @ index.js:42
renderWithHooks @ chunk-SJD7EFYL.js:69
updateFunctionComponent @ chunk-SJD7EFYL.js:69
beginWork @ chunk-SJD7EFYL.js:71
callCallback2 @ chunk-SJD7EFYL.js:2
invokeGuardedCallbackDev @ chunk-SJD7EFYL.js:2
invokeGuardedCallback @ chunk-SJD7EFYL.js:2
beginWork$1 @ chunk-SJD7EFYL.js:90
performUnitOfWork @ chunk-SJD7EFYL.js:90
workLoopSync @ chunk-SJD7EFYL.js:90
performSyncWorkOnRoot @ chunk-SJD7EFYL.js:90
(anonymous) @ chunk-SJD7EFYL.js:9
unstable_runWithPriority @ chunk-SJD7EFYL.js:1
runWithPriority$1 @ chunk-SJD7EFYL.js:9
flushSyncCallbackQueueImpl @ chunk-SJD7EFYL.js:9
flushSyncCallbackQueue @ chunk-SJD7EFYL.js:9
discreteUpdates$1 @ chunk-SJD7EFYL.js:90
discreteUpdates @ chunk-SJD7EFYL.js:2
dispatchDiscreteEvent @ chunk-SJD7EFYL.js:8

**Comment by elirov** [comment]
confirmed that downgrading to 4.1.0 solves the issue.

**Comment by nutboltu** [comment]
This issue is fixed in [4.2.1](https://github.com/linearlabs-workspace/storybook-addon-mock/releases/tag/4.2.1)
