### ISSUE TITLE
`forEach` and other properties missing from response headers

### ISSUE THREAD

**Issue by katarzynaB99** [linearlabs-workspace/storybook-addon-mock#186]
Hello! In our projects, the headers of the received response are inspected by using the `forEach` method of the [`Headers` object](https://developer.mozilla.org/en-US/docs/Web/API/Headers/forEach).

It seems like `forEach` and a couple other properties are missing, which breaks our Storybook integration.

I've noticed that every property for headers is explicitly added in the [`response.js` file](https://github.com/linearlabs-workspace/storybook-addon-mock/blob/f7d34743e5954e501222e32129bca2c3c258e784/packages/mock-addon/src/utils/response.js#L24). Is there a specific reason for why it's done this way, over just using the [`Headers` constructor](https://developer.mozilla.org/en-US/docs/Web/API/Headers/Headers)?

I'd be happy to provide a pull request for this change, which would either make use of the built-in constructor, or add the missing properties (depending on what's preferred) 😄

**Comment by katarzynaB99** [comment]
Created a PR with a proposed solution: #187

**Comment by wasyl078** [comment]
I also encountered this problem in my project. Fixing that would be great!

**Comment by nutboltu** [comment]
Thanks, @katarzynaB99, for your contribution. This feature is now available in version [4.3.0](https://github.com/linearlabs-workspace/storybook-addon-mock/releases/tag/4.3.0)
