### ISSUE TITLE
Not properly mocking requests made with ofetch

### ISSUE THREAD

**Issue by samturrell** [linearlabs-workspace/storybook-addon-mock#188]
ofetch (https://github.com/unjs/ofetch) checks for if the `response.body` is set on the response. If not it doesn't parse or return anything as it assumes it is an empty response.

Would it be possible to populate the `body` also?

**Comment by nutboltu** [comment]
This issue is fixed in version [4.3.0](https://github.com/linearlabs-workspace/storybook-addon-mock/releases/tag/4.3.0)

**Comment by samturrell** [comment]
Thanks, much appreciated 🙌
