### ISSUE TITLE
Undeclared dependency on `prop-types`

### ISSUE THREAD

**Issue by anomiex** [linearlabs-workspace/storybook-addon-mock#190]
The package depends on `prop-types` at runtime, but this dependency is not declared.

This happens to work with npm's hoisting since this package is usually used alongside other packages that do declare a dependency on `prop-types`, but will fail in pnpm with hoisting disabled and in yarn with p'n'p.

Here is a fairly minimal project that can be used for testing: [test.zip](https://github.com/linearlabs-workspace/storybook-addon-mock/files/12600009/test.zip)

**Comment by nutboltu** [comment]
This package is added as a dependency in version [4.3.0](https://github.com/linearlabs-workspace/storybook-addon-mock/releases/tag/4.3.0)
